CREATE USER OT_SRC_SRI1 IDENTIFIED BY admin;

grant all PRIVILEGES TO OT_SRC_SRI1;

GRANT DBA TO OT_SRC_SRI1;


CREATE USER OT_SR_SRI2 IDENTIFIED BY admin;

grant all PRIVILEGES TO OT_SR_SRI2;

grant dba to OT_SR_SRI2;

